Homepage
include-davis/bloom-and-vine pull request #8
Opened 2023-03-03 04:10 UTC by ryyu444

Functioning Homepage w/ navbar, most of the homepage components, redirects, & footer (still need to implement IG posts)
P.S Thanks Austin >:)

2023-03-03 17:26 UTC, Austin2Shih commented
Backend stuff looks good!

2023-03-06 07:48 UTC, dorothyle requested changes
**Some overall comments:**
- change the pixels to em, this will come in handy when doing mobile wireframes and making responsive webpages
- make the classnames more unique and less general since elements with the same class names can have conflicting CSS stylings
- replace `id` with `className` even if the element shows up once. it's better practice to use classNames and by putting it in the same class, styling can affect multiple elements and reduce redundancy. 
- images should be uploaded in the `src\image` folder. I'll make this folder in main, so please pull from it and store all your images there instead of in the `Pages` folder. Make sure to reroute the images as well. 

**What to work on next:**
- change the tab title on each page
- CONTACT PAGE: page looks zoomed in; work on fixing that

2023-03-06 07:48 UTC, dorothyle commented on bloom-and-vine/src/Components/review-slider/ReviewSlider.css
> +    transition: 0.5s
missing semicolon

2023-03-06 07:48 UTC, dorothyle commented on bloom-and-vine/src/Components/review-slider/ReviewSlider.js
> +            <button id='backward-button' onClick={e => onClickHandler(e, 'back')}>
change id to class, then you can apply styling to that class instead of all buttons

2023-03-06 07:48 UTC, dorothyle commented on bloom-and-vine/src/Components/serviceBar.css
> +#servBar{
change `id` to `class`

2023-03-06 07:48 UTC, dorothyle commented on bloom-and-vine/src/Components/serviceBarElements.js
> +                <h3 className= "servHeader2" >{props.name}</h3>
needs better naming

2023-03-06 07:48 UTC, dorothyle commented on bloom-and-vine/src/Components/serviceBarList.js
> +        <div id = "servBar">
change `id` to `class`

2023-03-06 07:48 UTC, dorothyle commented on bloom-and-vine/src/Pages/Contact.js
> +                <svg width="40" height="40" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
extract svg into their own .svg file

2023-03-06 07:48 UTC, dorothyle commented on bloom-and-vine/src/Pages/Contact.css
> +input[type=date] {
date is too close to the edge of the text box. add padding on the left

2023-03-07 23:44 UTC, juliaalberto requested changes
Overall, good progress! Make sure each component matches the design as in the Figma file. And when writing the attributes, make sure they match their respective title and/or link. 

In addition to dorothy's review, what to work next is also the footer as the page links are overlapping the text.

2023-03-07 23:44 UTC, juliaalberto commented on bloom-and-vine/src/Pages/Contact.js
> +      {/* <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script> */}
Don't forget to add the nav bar and footer for this page

2023-03-07 23:44 UTC, juliaalberto commented on bloom-and-vine/src/Components/instagram-posts/components/InstagramPost.js
> +        location.href = permalink;
I am sure if this is a problem with my computer but I am getting an error message "Line 14:9:  Unexpected use of 'location'  no-restricted-globals"

2023-03-07 23:44 UTC, juliaalberto commented on bloom-and-vine/src/Components/carousel.css
> +  .arrow {
Style the arrow such that it matches with the Figma file

2023-03-07 23:44 UTC, juliaalberto commented on bloom-and-vine/src/Pages/Contact.css
> +input[type=submit] {
Actually, all of the inputs are too close to the edge of the textbox. add some space on the left side to add padding

2023-03-07 23:44 UTC, juliaalberto commented on bloom-and-vine/src/Pages/Contact.css
> +.Rightside-Screen {
The background on the right side of this page is white

2023-03-07 23:44 UTC, juliaalberto commented on bloom-and-vine/src/Pages/Contact.css
> +input[type=submit]:hover {
Don't forget to style the button with purple padding

2023-03-07 23:44 UTC, juliaalberto commented on bloom-and-vine/src/Pages/Contact.js
> +          <label for="subject">Message</label>
change the for, id, and name attribute to their respective titles. This is important for the autofill feature when filling out the form

2023-04-02 06:47 UTC, merged